export const PERMISSIONS = {
  // Pedidos
  VER_PEDIDOS: 'VER_PEDIDOS',
  CREAR_PEDIDOS: 'CREAR_PEDIDOS',
  EDITAR_PEDIDOS: 'EDITAR_PEDIDOS',
  ELIMINAR_PEDIDOS: 'ELIMINAR_PEDIDOS',

  // Mantenimiento
  VER_MANTENIMIENTO: 'VER_MANTENIMIENTO',
  CREAR_MANTENIMIENTO: 'CREAR_MANTENIMIENTO',
  EDITAR_MANTENIMIENTO: 'EDITAR_MANTENIMIENTO',
  ELIMINAR_MANTENIMIENTO: 'ELIMINAR_MANTENIMIENTO',

  // Comercial
  VER_COMERCIAL: 'VER_COMERCIAL',
  CREAR_COMERCIAL: 'CREAR_COMERCIAL',
  EDITAR_COMERCIAL: 'EDITAR_COMERCIAL',
  ELIMINAR_COMERCIAL: 'ELIMINAR_COMERCIAL',

  // Obras
  VER_OBRAS: 'VER_OBRAS',
  CREAR_OBRAS: 'CREAR_OBRAS',
  EDITAR_OBRAS: 'EDITAR_OBRAS',
  ELIMINAR_OBRAS: 'ELIMINAR_OBRAS',

  // Empresas & Contactos
  VER_EMPRESAS: 'VER_EMPRESAS',
  CREAR_EMPRESAS: 'CREAR_EMPRESAS',
  EDITAR_EMPRESAS: 'EDITAR_EMPRESAS',
  ELIMINAR_EMPRESAS: 'ELIMINAR_EMPRESAS',
  VER_CONTACTOS: 'VER_CONTACTOS',
  CREAR_CONTACTOS: 'CREAR_CONTACTOS',
  EDITAR_CONTACTOS: 'EDITAR_CONTACTOS',
  ELIMINAR_CONTACTOS: 'ELIMINAR_CONTACTOS',

  // Equipos y Categorias
  VER_EQUIPOS: 'VER_EQUIPOS',
  CREAR_EQUIPOS: 'CREAR_EQUIPOS',
  EDITAR_EQUIPOS: 'EDITAR_EQUIPOS',
  ELIMINAR_EQUIPOS: 'ELIMINAR_EQUIPOS',

  // Administracion y Roles
  GESTIONAR_ROLES: 'GESTIONAR_ROLES',
  GESTIONAR_USUARIOS: 'GESTIONAR_USUARIOS',

  // Ver otras vistas generales
  VER_OPERACIONES: 'VER_OPERACIONES',
  VER_COMPRAS: 'VER_COMPRAS',
  VER_RRHH: 'VER_RRHH',
  VER_PAGOS: 'VER_PAGOS',
  VER_CARTERA: 'VER_CARTERA',
  VER_JURIDICA: 'VER_JURIDICA',
  VER_PAPELERA: 'VER_PAPELERA',

  // Contabilidad / Siigo
  VER_CONTABILIDAD: 'VER_CONTABILIDAD',
  SINCRONIZAR_SIIGO: 'SINCRONIZAR_SIIGO',
} as const;

export type Permission = keyof typeof PERMISSIONS;

// Helper to get all permission values
export const ALL_PERMISSIONS = Object.values(PERMISSIONS);
